/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Lucas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuReservas = new javax.swing.JMenu();
        menuCadReserva = new javax.swing.JMenuItem();
        manuCadReserva = new javax.swing.JMenuItem();
        menuFinReserva = new javax.swing.JMenuItem();
        MenuConsumo = new javax.swing.JMenu();
        menuVenProduto = new javax.swing.JMenuItem();
        menuVenServicos = new javax.swing.JMenuItem();
        jmenu1 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        menuCadHospede = new javax.swing.JMenuItem();
        menuConHospede = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        menuCadQuartos = new javax.swing.JMenuItem();
        menuConQuarto = new javax.swing.JMenuItem();
        jmenu = new javax.swing.JMenu();
        menuCadFuncionario = new javax.swing.JMenuItem();
        menuConFuncionarios = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        manuConFornecedor = new javax.swing.JMenuItem();
        menuCadFornecedor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        manuCadProduto = new javax.swing.JMenuItem();
        menuConProduto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        manuCadServico = new javax.swing.JMenuItem();
        menuConServico = new javax.swing.JMenuItem();
        MenuRelatorios = new javax.swing.JMenu();
        Financeiro = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuFinanceiro = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        menuCadPagar = new javax.swing.JMenuItem();
        menuConPagar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuCadReceber = new javax.swing.JMenuItem();
        menuConReceber = new javax.swing.JMenuItem();
        menuFinBalanco = new javax.swing.JMenuItem();
        MenuFerramentas = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        MenuFerraments = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonSair.setText("Sair");
        ButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/1666647919423.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 670));

        MenuReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hotel_bell_doorbell_hotel_reception_icon_196778.png"))); // NOI18N
        MenuReservas.setText("Reservas   |");

        menuCadReserva.setText("Cadastrar Reserva");
        MenuReservas.add(menuCadReserva);

        manuCadReserva.setText("Consultar Reserva");
        MenuReservas.add(manuCadReserva);

        menuFinReserva.setText("Finalizar Reserva");
        menuFinReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFinReservaActionPerformed(evt);
            }
        });
        MenuReservas.add(menuFinReserva);

        jMenuBar1.add(MenuReservas);

        MenuConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cashier_machine_cash_register_pos_icon_225201.png"))); // NOI18N
        MenuConsumo.setText("Vendas   |");

        menuVenProduto.setText("Produtos");
        MenuConsumo.add(menuVenProduto);

        menuVenServicos.setText("Servicos");
        MenuConsumo.add(menuVenServicos);

        jMenuBar1.add(MenuConsumo);

        jmenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/signupsign_inscribirs_2798.png"))); // NOI18N
        jmenu1.setText("Cadastros   |");

        jMenu9.setText("Hospedes");

        menuCadHospede.setText("Cadastrar");
        menuCadHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospedeActionPerformed(evt);
            }
        });
        jMenu9.add(menuCadHospede);

        menuConHospede.setText("Consultar");
        jMenu9.add(menuConHospede);

        jmenu1.add(jMenu9);

        jMenu10.setText("Quartos");

        menuCadQuartos.setText("Cadastrar");
        jMenu10.add(menuCadQuartos);

        menuConQuarto.setText("Consultar");
        jMenu10.add(menuConQuarto);

        jmenu1.add(jMenu10);

        jmenu.setText("Funcionarios");

        menuCadFuncionario.setText("Cadastrar");
        menuCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFuncionarioActionPerformed(evt);
            }
        });
        jmenu.add(menuCadFuncionario);

        menuConFuncionarios.setText("Consultar");
        menuConFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConFuncionariosActionPerformed(evt);
            }
        });
        jmenu.add(menuConFuncionarios);

        jmenu1.add(jmenu);

        jMenu1.setText("Fornecedores");

        manuConFornecedor.setText("Consultar");
        jMenu1.add(manuConFornecedor);

        menuCadFornecedor.setText("Cadastrar");
        jMenu1.add(menuCadFornecedor);

        jmenu1.add(jMenu1);

        jMenu2.setText("Produtos");

        manuCadProduto.setText("Cadastrar");
        jMenu2.add(manuCadProduto);

        menuConProduto.setText("Consultar");
        jMenu2.add(menuConProduto);

        jmenu1.add(jMenu2);

        jMenu3.setText("Servicos");

        manuCadServico.setText("Cadastrar");
        jMenu3.add(manuCadServico);

        menuConServico.setText("Consultar");
        menuConServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConServicoActionPerformed(evt);
            }
        });
        jMenu3.add(menuConServico);

        jmenu1.add(jMenu3);

        jMenuBar1.add(jmenu1);

        MenuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/5_icon-icons.com_68890.png"))); // NOI18N
        MenuRelatorios.setText("Relatorios   |");

        Financeiro.setText("Financeiro");

        jMenuItem4.setText("Contas a Pagar");
        Financeiro.add(jMenuItem4);

        jMenuItem5.setText("Contas a Receber");
        Financeiro.add(jMenuItem5);

        jMenuItem6.setText("Balanco");
        Financeiro.add(jMenuItem6);

        MenuRelatorios.add(Financeiro);

        jMenu7.setText("Reservas");

        jMenuItem7.setText("Quartos Disponiveis");
        jMenu7.add(jMenuItem7);

        jMenuItem8.setText("Quartos Ocupados");
        jMenu7.add(jMenuItem8);

        jMenuItem9.setText("Reservas Futuras");
        jMenu7.add(jMenuItem9);

        MenuRelatorios.add(jMenu7);

        jMenu8.setText("Vendas");
        MenuRelatorios.add(jMenu8);

        jMenuItem1.setText("Hospedes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuRelatorios.add(jMenuItem1);

        jMenuItem2.setText("Funcionarios");
        MenuRelatorios.add(jMenuItem2);

        jMenuItem3.setText("Fornecedores");
        MenuRelatorios.add(jMenuItem3);

        jMenuBar1.add(MenuRelatorios);

        MenuFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coin_money_icon-icons.com_51091.png"))); // NOI18N
        MenuFinanceiro.setText("Financeiro   |");

        jMenu4.setText("Contas a Pagar");

        menuCadPagar.setText("Cadastrar");
        jMenu4.add(menuCadPagar);

        menuConPagar.setText("Consultar");
        jMenu4.add(menuConPagar);

        MenuFinanceiro.add(jMenu4);

        jMenu5.setText("Contas a Receber");

        menuCadReceber.setText("Cadastrar");
        jMenu5.add(menuCadReceber);

        menuConReceber.setText("Consultar");
        jMenu5.add(menuConReceber);

        MenuFinanceiro.add(jMenu5);

        menuFinBalanco.setText("Balanço");
        MenuFinanceiro.add(menuFinBalanco);

        jMenuBar1.add(MenuFinanceiro);

        MenuFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3668850-insurance-protection-safety-shield_108037.png"))); // NOI18N
        MenuFerramentas.setText("Seguranca   |");

        jMenuItem11.setText("Fazer Backup");
        MenuFerramentas.add(jMenuItem11);

        jMenuItem12.setText("Restaurar Backup");
        MenuFerramentas.add(jMenuItem12);

        jMenuBar1.add(MenuFerramentas);

        MenuFerraments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3592847-general-office-repair-repair-tool-screwdriver-tools-wrench_107766.png"))); // NOI18N
        MenuFerraments.setText("Ferramentas   |");

        jMenuItem13.setText("Sobre o Sistema");
        MenuFerraments.add(jMenuItem13);

        jMenu6.setText("Tela de Fundo");

        jMenuItem10.setText("Add Imagem");
        jMenu6.add(jMenuItem10);

        jMenuItem14.setText("Remover Imagem");
        jMenu6.add(jMenuItem14);

        jMenuItem15.setText("Restaurar Padrao");
        jMenu6.add(jMenuItem15);

        MenuFerraments.add(jMenu6);

        jMenuBar1.add(MenuFerraments);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospedeActionPerformed

    private void menuCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadFuncionarioActionPerformed

    private void menuConFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConFuncionariosActionPerformed

    private void menuConServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConServicoActionPerformed

    private void menuFinReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFinReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFinReservaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSair;
    private javax.swing.JMenu Financeiro;
    private javax.swing.JMenu MenuConsumo;
    private javax.swing.JMenu MenuFerramentas;
    private javax.swing.JMenu MenuFerraments;
    private javax.swing.JMenu MenuFinanceiro;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenu MenuReservas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jmenu;
    private javax.swing.JMenu jmenu1;
    private javax.swing.JMenuItem manuCadProduto;
    private javax.swing.JMenuItem manuCadReserva;
    private javax.swing.JMenuItem manuCadServico;
    private javax.swing.JMenuItem manuConFornecedor;
    private javax.swing.JMenuItem menuCadFornecedor;
    private javax.swing.JMenuItem menuCadFuncionario;
    private javax.swing.JMenuItem menuCadHospede;
    private javax.swing.JMenuItem menuCadPagar;
    private javax.swing.JMenuItem menuCadQuartos;
    private javax.swing.JMenuItem menuCadReceber;
    private javax.swing.JMenuItem menuCadReserva;
    private javax.swing.JMenuItem menuConFuncionarios;
    private javax.swing.JMenuItem menuConHospede;
    private javax.swing.JMenuItem menuConPagar;
    private javax.swing.JMenuItem menuConProduto;
    private javax.swing.JMenuItem menuConQuarto;
    private javax.swing.JMenuItem menuConReceber;
    private javax.swing.JMenuItem menuConServico;
    private javax.swing.JMenuItem menuFinBalanco;
    private javax.swing.JMenuItem menuFinReserva;
    private javax.swing.JMenuItem menuVenProduto;
    private javax.swing.JMenuItem menuVenServicos;
    // End of variables declaration//GEN-END:variables
}
